### ISSUE TITLE
Can not find the db files

### ISSUE THREAD

**Issue by boosis** [tutumcloud/mongodb#34]
I have the following docker-compose setup
```yaml
dataonly:
  image: busybox
  volumes:
    - /Users/boosis/work/personal/data-only/mongo:/data
  command: "true"

mongo:
  image: tutum/mongodb
  volumes_from:
    - dataonly
  environment:
    - AUTH=no
    - JOURNALING=yes
  ports:
    - "27017:27017"
    - "28018:28018"
```

which brings up a mongo db container and works just fine. But for some reason /Users/boosis/work/personal/data-only/mongo is empty.

If I go in to mongo container and create a file in /data directory I can see it on my mac, but I cannot see any of the mongodb files.
