### ISSUE TITLE
Auth erro on Docker Cloud

### ISSUE THREAD

**Issue by nicky-lenaers** [tutumcloud/mongodb#43]
I moved from Tutum to Docker Cloud.

I have a database called ``mydatabase`` that is to be used by the app.

On the first deploy, I get this error:
```
Unhandled rejection MongoError: not authorized for query on mydatabase.system.indexes
web-1 | 2016-02-17T23:47:46.283077281Z     at Function.MongoError.create (/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
web-1 | 2016-02-17T23:47:46.283086725Z     at queryCallback (/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:267:34)
web-1 | 2016-02-17T23:47:46.283109616Z     at Callbacks.emit (/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
web-1 | 2016-02-17T23:47:46.283118032Z     at null.messageHandler (/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
web-1 | 2016-02-17T23:47:46.283126078Z     at Socket.<anonymous> (/app/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
web-1 | 2016-02-17T23:47:46.283135361Z     at emitOne (events.js:77:13)
web-1 | 2016-02-17T23:47:46.283193121Z     at Socket.emit (events.js:169:7)
web-1 | 2016-02-17T23:47:46.283203810Z     at readableAddChunk (_stream_readable.js:146:16)
web-1 | 2016-02-17T23:47:46.283211715Z     at Socket.Readable.push (_stream_readable.js:110:10)
web-1 | 2016-02-17T23:47:46.283219050Z     at TCP.onread (net.js:523:20)
```

My ``stackfile``:
```
mongo:
  image: 'tutum/mongodb:latest'
  environment:
    - MONGODB_PASS=<password>
  ports:
    - '27017:27017'
    - '28017:28017'
web:
  image: 'username/repo:latest'
  links:
    - 'mongo:mongo'
  ports:
    - '80:3000'
  restart: always
```

Am I missing configuration?
